### ISSUE TITLE
Dans l'exercise 'transitions_smart_Ibranch' il y a probablement un problème d'indice

### ISSUE THREAD

**Issue by chambart** [xavierleroy/cdf-sem-meca#1]
Le lemme pour montrer que `smart_Ibranch d` saute bien au dessus de `d` instruction a l'air de supposer que le résultat de `smart_Ibranch d` est de longueur 1. Il faut probablement remplacer 

https://github.com/xavierleroy/cdf-sem-meca/blob/39c5f89dbfb8d3c1e3f9a79799609479badb3139/Compil.v#L646
Par
```coq
  pc' = pc + (codelen (smart_Ibranch d)) + d ->
```

**Comment by xavierleroy** [comment]
Bien vu, merci!  C'est corrigé.
