### ISSUE TITLE
Make: Unable to locate library PropExtensionality with prefix Coq.

### ISSUE THREAD

**Issue by AlainLich** [xavierleroy/cdf-sem-meca#2]
Are there required libraries? Versions?  Other requirements before doing "Make" ?
Thanks for any help/documentation.

On Ubuntu, installed Coq using: apt-get install coq; got a not too new version:
The Coq Proof Assistant, version 8.6 (October 2017)
compiled on Oct 28 2017 14:23:55 with OCaml 4.05.0

Then make gives
cdf-sem-meca$ make
Makefile:4: avertissement : surchargement de la recette pour la cible « CoqMakefile »
CoqMakefile:238: avertissement : ancienne recette ignorée pour la cible « CoqMakefile »
"coqc"  -q  -R "." CDF   SepLogic
File "./SepLogic.v", line 2, characters 49-67:
Error: Unable to locate library PropExtensionality with prefix Coq.
CoqMakefile:249: recipe for target 'SepLogic.vo' failed

**Comment by xavierleroy** [comment]
You're correct, the PropExtensionality library was added in Coq 8.7 and is not available in 8.6.

You're also correct that Coq 8.6 is the version packaged by Ubuntu 18.04 LTS.  Even Debian stable is now at Coq 8.9...

Can you upgrade Coq?  See for example this PPA: https://launchpad.net/~jgross-h/+archive/ubuntu/coq-8.10-daily

In the meantime I'll see what I can do to make the Coq sources compatible with 8.6.

**Comment by xavierleroy** [comment]
There are other incompatibilities with Coq 8.6: `String.eqb` missing in stdlib, `lia` tactic less powerful...  I'm afraid I'm not going to support Coq 8.6 in the end.

**Comment by AlainLich** [comment]
**Thanks**, I got it to work with this version cloned from github; 

> The Coq Proof Assistant, version 8.10.2 (January 2020)
> compiled on Jan 9 2020 20:10:55 with OCaml 4.05.0
> 

However, version 8.8 is not good enough:
```
"coqc"  -q  -R "." CDF   IMP
     = 3
     : Z
     = fun s : store => s "x" + 9
     : store -> Z
     = Some (4, 2)
     : option (Z * Z)
"coqc"  -q  -R "." CDF   SepLogic
File "./SepLogic.v", line 424, characters 68-71:
Error: In nested Ltac calls to "lia", "Lia.lia" and "xlia (tactic)", last call failed.
Tactic failure:  Cannot find witness.
```
